### ISSUE TITLE
Won't Work

### ISSUE THREAD

**Issue by joelliott** [swkim01/webiopi-dht#2]
I've followed all steps on Pi 2 running Noobs vs 1_9_0 with Raspbian but when restarting WebIOPi-0.7.1 after editing webiopi config file is get a status of active (exited) instead of running?  
I'm not running anything else on Pi except for your scripts line by line but keep getting this state of WebIOPi exited everytime.

Is there something different or a different os that your running to make this work?

Any help is appreciated. 

Thank You

**Comment by swkim01** [comment]
Did you install WebIOPi with python 2.7? Please check out readme again.
Then, you can see error message during running webiopi manually.
sudo /etc/init.d/webiopi stop
sudo webipi -d -c /etc/webiopi/config

**Comment by joelliott** [comment]
Thank you for the reply

I did install WebIOPi with python 2.7, I've re-read the readme page again, and also did the instructions listed below:

sudo /etc/init.d/webiopi stop
sudo webipi -d -c /etc/webiopi/config

results:

everything loads except for the current error message as attached.

I've read and re-read the readme file over about 10 different times along with countless times of starting from scratch with new os.  I relent that I am a noob to these platforms but alas, I can't seen to find this error.  The dht.xx is loaded in the sensor file as you indicated in the readme along with the _init_ file, along with the patch for pi2.  everything installs correctly and I can pull the sensor settings up thru the shell using the DHT examples file but can't seem to get WebIOPi to see the sensor for some reason.

Any further assistance would greatly help.

along with my constant reading of the "readme" file, I would like to note one thing I did realize:

the DHT download website is:

https://github.com/adafruit/Adafruit_Python_DHT.git

you have listed in the readme:

https://github.com.adafruit/Adafruit_Python_DHT.git

I noticed the .adafruit vs the /adafruit as I couldn't reach the site and went there via web browser before.

Hope this helps for any other noobs.

Sincerely,

Jonathan Elliott

**Comment by swkim01** [comment]
Python 2.7.9 has bug of imp.find_module() method that can't find modules in egg module file(see [here](https://github.com/mbedmicro/mbed/issues/1077)), thus webiopi can't load any device module.

I found two methods to solve this problem. One simplest way is to unzip that file.

``` shell
cd /usr/local/lib/python2.7/dist-packages
sudo unzip WebIOPi-0.7.1-py2.7-linux-armv7l.egg
```

The other way is to replace two lines in [WebIOPi's source path]/python/webiopi/devices/manager.py

``` shell
(fp, pathname, stuff) = imp.find_module(package.__name__.replace(".", "/") + "/" + driver)
module = imp.load_module(driver, fp, pathname, stuff)
```

to

``` shell
import importlib
module = importlib.import_module(package.__name__ + "." + driver)
```

Then, install webiopi python module again.

``` shell
cd [WebIOPi's source path]/python
sudo python setup.py install
```

Thank you for your report.

**Comment by joelliott** [comment]
Swkim01,

Wanted to make sure I fully investigated this next issue before posting.  Your previous fix for the DHT22 temp sensor worked perfectly.

For anyone wondering, to change temp from Celsius to Fahrenheit using example projects, go to webiopi-dht examples index.html.

edit tmp.getCelcius to tmp.getFahrenheit(temperatureCallback) ;

also in function to display the temperature change ("Temp: " + data + "°C") ;

to ("Temp: " + data + "°F") ;

The issue I have found in the project is the Led pin set for low and high points for the temp sensor.  As this is running python 2.7 the line in the script GPIO = webiopi.GPIO causes an error.

Here is the error:

'Humidity'] - DHT11(pin=18) mapped to REST API /devices/dht0
2016-04-06 02:53:42 - WebIOPi - INFO - Loading myproject from /home/pi/webiopi-dht/examples/python/script.py
2016-04-06 02:53:42 - WebIOPi - ERROR - 'module' object has no attribute 'GPIO'
Traceback (most recent call last):
  File "build/bdist.linux-armv7l/egg/webiopi/**main**.py", line 75, in <module>
    main(sys.argv)
  File "build/bdist.linux-armv7l/egg/webiopi/**main**.py", line 69, in main
    server = Server(port=port, configfile=configfile, scriptfile=scriptfile)
  File "build/bdist.linux-armv7l/egg/webiopi/server/**init**.py", line 75, in **init**
    loader.loadScript(name, source, self.restHandler)
  File "build/bdist.linux-armv7l/egg/webiopi/utils/loader.py", line 8, in loadScript
    script = imp.load_source(name, source)
  File "/home/pi/webiopi-dht/examples/python/script.py", line 3, in <module>
    GPIO = webiopi.GPIO
AttributeError: 'module' object has no attribute 'GPIO'

I've researched some other examples in the forums such as:

http://www.knight-of-pi.org/webiopi-a-simple-but-great-web-api-for-the-raspberry-pi/

and

http://webiopi.trouch.com/issues/97/

although these issue's had resolves to them, the fix was for WebIOPi running on python3 not 2.7.  do you know of a fix for this issue.  I can run script w/o error in python 3 by itself (not thru WebIOPI 2.7) but this doesn't resolve running this in python2.7 mode for use of DHT22 temp sensor.

Any help would be greatly helpful

also, thank you for the reference on the prior update.   Just trying to help with any issue's I come across.

Joelliot

Issue #097 [New/open] - AttributeError: 'module' object ...http://webiopi.trouch.com/issues/97/
webiopi.trouch.com
Comment 3. Posted by andreas.riegg. Are you sure that the compiling of the native C interface module of WebIOPi for the native GPIO ports really succeeded?

[http://www.knight-of-pi.org/wp-content/uploads/2015/12/logo_knight_of_pi_5.png]http://www.knight-of-pi.org/webiopi-a-simple-but-great-web-api-for-the-raspberry-pi/

WebIOPi: a simple but great web api for the Raspberry Pihttp://www.knight-of-pi.org/webiopi-a-simple-but-great-web-api-for-the-raspberry-pi/
www.knight-of-pi.org
WebIOPi is an absolutely great freeware web interface for the Raspberry Pi, a tribute to the developers! The setup is easy and finished in less than 30 minutes: the ...

**Comment by swkim01** [comment]
I found Python 2.7.9 can't load module in a directory start with "_". The solution is to change the first line of setup.py to "from distutils.core import setup, Extension" and replace "_webiopi" string to "webiopi" in all source files.

However, instead I made new patch file to do all of things.You have to clean or delete all webiopi related files in /usr/local/lib/python2.7/dist-packages and then follow readme.md.

Good luck!

**Comment by joelliott** [comment]
Thank you for the resolve.  Works perfectly.
